"""initial_schema

Revision ID: f2efb29e03b1
Revises: 
Create Date: 2026-09-07 10:02:34.531094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# F1.3: import del tipo custom ``app.models.base.GUID`` para que las
# columnas ``sa.Column('id', app.models.base.GUID(), ...)`` se ejecuten.
# Sin este import, alembic revienta con ``NameError: name 'app' is not
# defined`` al hacer ``alembic upgrade head``.
import app.models.base  # noqa: F401  ( registra GUID en app.models.base )


# revision identifiers, used by Alembic.
revision: str = 'f2efb29e03b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_consents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_version', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_consents_document_type'), 'legal_consents', ['document_type'], unique=False)
    op.create_index(op.f('ix_legal_consents_user_id'), 'legal_consents', ['user_id'], unique=False)
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_theme', sa.String(length=20), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.Enum('GASTRO', 'RETAIL', 'SERVICES', 'BEAUTY', 'EDUCATION', 'HEALTH', 'OTHER', name='industry'), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'GROW', 'PRO', 'BUSINESS', name='tenant_plan'), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'SUSPENDED', name='tenant_status'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('wow_score', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('active_branches', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_industry'), 'tenants', ['industry'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('default_role', sa.Enum('OWNER', 'ADMIN', 'STAFF', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.Enum('MARKETING', 'GROWTH', 'AUTOMATION', 'MARKETPLACE', 'HELP', 'ROUTER', name='ai_agent_kind'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='ai_conversation_status'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_status'), 'ai_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_ai_conversations_tenant_id'), 'ai_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_metrics_daily',
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.Enum('MARKETING', 'GROWTH', 'AUTOMATION', 'MARKETPLACE', 'HELP', 'ROUTER', name='ai_metric_agent'), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('fallback', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('timeouts', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_metrics_daily_agent'), 'ai_metrics_daily', ['agent'], unique=False)
    op.create_index(op.f('ix_ai_metrics_daily_day'), 'ai_metrics_daily', ['day'], unique=False)
    op.create_index(op.f('ix_ai_metrics_daily_tenant_id'), 'ai_metrics_daily', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.String(length=4), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('ix_audit_tenant_actor', 'audit_logs', ['tenant_id', 'actor_user_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('PASSWORD_RESET', 'EMAIL_VERIFICATION', 'INVITATION', name='token_type'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_auth_tokens_type'), 'auth_tokens', ['type'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PREVIEW_READY', 'AWAITING_CONFIRMATION', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='automation_status'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_insight_id', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_url', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_meta', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_exec_action', 'automation_executions', ['action_type'], unique=False)
    op.create_index('ix_auto_exec_tenant_created', 'automation_executions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_auto_exec_user_created', 'automation_executions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_automation_executions_action_type'), 'automation_executions', ['action_type'], unique=False)
    op.create_index(op.f('ix_automation_executions_source_insight_id'), 'automation_executions', ['source_insight_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_status'), 'automation_executions', ['status'], unique=False)
    op.create_index(op.f('ix_automation_executions_tenant_id'), 'automation_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_user_id'), 'automation_executions', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=False)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('business_costs',
    sa.Column('owner_salary_cents', sa.Integer(), nullable=False),
    sa.Column('workers_salary_cents', sa.Integer(), nullable=False),
    sa.Column('productive_hours_per_month', sa.Integer(), nullable=False),
    sa.Column('target_margin_pct', sa.Integer(), nullable=False),
    sa.Column('rent_cents', sa.Integer(), nullable=False),
    sa.Column('electricity_cents', sa.Integer(), nullable=False),
    sa.Column('water_cents', sa.Integer(), nullable=False),
    sa.Column('gas_cents', sa.Integer(), nullable=False),
    sa.Column('software_cents', sa.Integer(), nullable=False),
    sa.Column('advertising_cents', sa.Integer(), nullable=False),
    sa.Column('payment_commission_cents', sa.Integer(), nullable=False),
    sa.Column('packaging_cents', sa.Integer(), nullable=False),
    sa.Column('maintenance_cents', sa.Integer(), nullable=False),
    sa.Column('depreciation_cents', sa.Integer(), nullable=False),
    sa.Column('waste_pct', sa.Integer(), nullable=False),
    sa.Column('is_na', sa.JSON(), nullable=False),
    sa.Column('total_fixed_cents', sa.Integer(), nullable=False),
    sa.Column('cost_hour_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_costs_tenant_id'), 'business_costs', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', app.models.base.GUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent_cents', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('last_order_at', sa.String(length=40), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('accepts_marketing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('segmento', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('insumos',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('reserved', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('reorder_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('waste_pct', sa.Float(), nullable=False),
    sa.Column('last_cost_cents', sa.Integer(), nullable=False),
    sa.Column('avg_cost_cents', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_na', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumos_name'), 'insumos', ['name'], unique=False)
    op.create_index(op.f('ix_insumos_sku'), 'insumos', ['sku'], unique=False)
    op.create_index(op.f('ix_insumos_tenant_id'), 'insumos', ['tenant_id'], unique=False)
    op.create_table('landing_configs',
    sa.Column('hero_title', sa.String(length=200), nullable=False),
    sa.Column('hero_subtitle', sa.String(length=400), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=60), nullable=False),
    sa.Column('hero_cta_url', sa.String(length=500), nullable=True),
    sa.Column('brand_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('contact_whatsapp', sa.String(length=40), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_address', sa.String(length=500), nullable=True),
    sa.Column('social_instagram', sa.String(length=80), nullable=True),
    sa.Column('social_facebook', sa.String(length=80), nullable=True),
    sa.Column('social_tiktok', sa.String(length=80), nullable=True),
    sa.Column('show_categories', sa.Boolean(), nullable=False),
    sa.Column('show_featured_products', sa.Boolean(), nullable=False),
    sa.Column('show_promotions', sa.Boolean(), nullable=False),
    sa.Column('show_branches', sa.Boolean(), nullable=False),
    sa.Column('show_contact', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=400), nullable=True),
    sa.Column('seo_image_url', sa.String(length=500), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('extra_blocks', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_configs_tenant_id'), 'landing_configs', ['tenant_id'], unique=False)
    op.create_table('loyalty_campaigns',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reward_label', sa.String(length=160), nullable=False),
    sa.Column('stamps_required', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('strip_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('metal_c1', sa.String(length=7), nullable=True),
    sa.Column('metal_c2', sa.String(length=7), nullable=True),
    sa.Column('metal_c3', sa.String(length=7), nullable=True),
    sa.Column('metal_c4', sa.String(length=7), nullable=True),
    sa.Column('metal_c5', sa.String(length=7), nullable=True),
    sa.Column('metal_angle', sa.Integer(), nullable=True),
    sa.Column('sheen_opacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cashier_pin', sa.String(length=64), nullable=True),
    sa.Column('pin_hint', sa.String(length=40), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=False),
    sa.Column('total_stamps_issued', sa.Integer(), nullable=False),
    sa.Column('total_rewards_redeemed', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.CheckConstraint('stamps_required BETWEEN 2 AND 50', name='ck_stamps_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loyalty_campaigns_tenant_active', 'loyalty_campaigns', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_loyalty_campaigns_tenant_id'), 'loyalty_campaigns', ['tenant_id'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.String(length=40), nullable=False),
    sa.Column('wizard_data', sa.JSON(), nullable=False),
    sa.Column('wow_score', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_states_tenant_id'), 'onboarding_states', ['tenant_id'], unique=False)
    op.create_table('promotions',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('promo_type', sa.Enum('PERCENT', 'FIXED', 'BUY_X_GET_Y', 'FREE_SHIPPING', 'BUNDLE', name='promotion_type'), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENT', 'FIXED', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('min_purchase_cents', sa.Integer(), nullable=False),
    sa.Column('max_discount_cents', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_customer', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('applies_to_all', sa.Boolean(), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('category_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('badge_text', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=False)
    op.create_index(op.f('ix_promotions_tenant_id'), 'promotions', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'STAFF', 'VIEWER', name='membership_role'), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by', app.models.base.GUID(), nullable=True),
    sa.Column('last_login_at', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_entity_id'), 'uploads', ['entity_id'], unique=False)
    op.create_index(op.f('ix_uploads_entity_type'), 'uploads', ['entity_type'], unique=False)
    op.create_index(op.f('ix_uploads_tenant_id'), 'uploads', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(length=2000), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_event'), 'webhook_deliveries', ['event'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=120), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.String(length=40), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('user_id', app.models.base.GUID(), nullable=True),
    sa.Column('conversation_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent', sa.Enum('MARKETING', 'GROWTH', 'AUTOMATION', 'MARKETPLACE', 'HELP', 'ROUTER', name='ai_log_agent'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FALLBACK', 'ERROR', 'TIMEOUT', 'RATE_LIMITED', name='ai_log_status'), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tools_called', sa.JSON(), nullable=True),
    sa.Column('circuit_state_before', sa.String(length=20), nullable=True),
    sa.Column('circuit_state_after', sa.String(length=20), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_agent'), 'ai_logs', ['agent'], unique=False)
    op.create_index(op.f('ix_ai_logs_conversation_id'), 'ai_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_status'), 'ai_logs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_logs_tenant_id'), 'ai_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_user_id'), 'ai_logs', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', 'SYSTEM', name='ai_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=True),
    sa.Column('tool_call_id', sa.String(length=80), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('agent', sa.Enum('MARKETING', 'GROWTH', 'AUTOMATION', 'MARKETPLACE', 'HELP', 'ROUTER', name='ai_message_agent'), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_tenant_id'), 'ai_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', app.models.base.GUID(), nullable=True),
    sa.Column('branch_id', app.models.base.GUID(), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('promotion_code', sa.String(length=40), nullable=True),
    sa.Column('promotion_ids', sa.JSON(), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_customer_id'), 'carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_carts_session_id'), 'carts', ['session_id'], unique=False)
    op.create_index(op.f('ix_carts_tenant_id'), 'carts', ['tenant_id'], unique=False)
    op.create_table('customer_passes',
    sa.Column('campaign_id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stamps_current', sa.Integer(), nullable=False),
    sa.Column('rewards_earned', sa.Integer(), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('apple_pass_url', sa.String(length=500), nullable=True),
    sa.Column('google_pass_jwt', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stamp_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.CheckConstraint('stamps_current >= 0', name='ck_stamps_nonneg'),
    sa.ForeignKeyConstraint(['campaign_id'], ['loyalty_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('tenant_id', 'campaign_id', 'customer_id', name='uq_pass_per_customer_campaign')
    )
    op.create_index(op.f('ix_customer_passes_campaign_id'), 'customer_passes', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_customer_passes_customer_id'), 'customer_passes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_passes_tenant_id'), 'customer_passes', ['tenant_id'], unique=False)
    op.create_index('ix_passes_tenant_status', 'customer_passes', ['tenant_id', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'DELIVERED', 'CANCELED', name='order_status'), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=True),
    sa.Column('branch_id', app.models.base.GUID(), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('promotion_ids', sa.JSON(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('qr_code_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=False)
    op.create_index(op.f('ix_orders_qr_code_id'), 'orders', ['qr_code_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', app.models.base.GUID(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('compare_at_cents', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('production_time_min', sa.Integer(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'OUT_OF_STOCK', 'ARCHIVED', name='product_status'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.Enum('CATALOG', 'PRODUCT', 'CATEGORY', 'PROMOTION', 'LANDING', 'EXTERNAL_URL', 'TABLE', name='qr_target'), nullable=False),
    sa.Column('target_id', app.models.base.GUID(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('branch_id', app.models.base.GUID(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('unique_scans', sa.Integer(), nullable=False),
    sa.Column('conversion_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_codes_branch_id'), 'qr_codes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_short_code'), 'qr_codes', ['short_code'], unique=True)
    op.create_index(op.f('ix_qr_codes_target_id'), 'qr_codes', ['target_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_tenant_id'), 'qr_codes', ['tenant_id'], unique=False)
    op.create_table('ai_traces',
    sa.Column('log_id', app.models.base.GUID(), nullable=True),
    sa.Column('conversation_id', app.models.base.GUID(), nullable=True),
    sa.Column('step', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_id'], ['ai_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_traces_conversation_id'), 'ai_traces', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_traces_log_id'), 'ai_traces', ['log_id'], unique=False)
    op.create_index(op.f('ix_ai_traces_step'), 'ai_traces', ['step'], unique=False)
    op.create_index(op.f('ix_ai_traces_tenant_id'), 'ai_traces', ['tenant_id'], unique=False)
    op.create_table('bookings',
    sa.Column('branch_id', app.models.base.GUID(), nullable=True),
    sa.Column('customer_id', app.models.base.GUID(), nullable=True),
    sa.Column('product_id', app.models.base.GUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELED', 'NO_SHOW', name='booking_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('staff_name', sa.String(length=120), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_branch_id'), 'bookings', ['branch_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_starts_at'), 'bookings', ['starts_at'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('branch_products',
    sa.Column('branch_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_products_branch_id'), 'branch_products', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_products_product_id'), 'branch_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_branch_products_tenant_id'), 'branch_products', ['tenant_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=60), nullable=True),
    sa.Column('product_image', sa.String(length=500), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('invoices',
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'CANCELED', 'VOIDED', name='invoice_status'), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_tax_id', sa.String(length=40), nullable=True),
    sa.Column('customer_tax_id_type', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_breakdown', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=60), nullable=True),
    sa.Column('product_image', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('pass_stamps',
    sa.Column('pass_id', app.models.base.GUID(), nullable=False),
    sa.Column('campaign_id', app.models.base.GUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('scanned_by', app.models.base.GUID(), nullable=True),
    sa.Column('cashier_pin_validated', sa.Boolean(), nullable=False),
    sa.Column('device_fp', sa.String(length=64), nullable=True),
    sa.Column('qr_token_jti', sa.String(length=64), nullable=True),
    sa.Column('stamps_after', sa.Integer(), nullable=False),
    sa.Column('reward_unlocked', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['loyalty_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pass_id'], ['customer_passes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pass_stamps_pass_id'), 'pass_stamps', ['pass_id'], unique=False)
    op.create_index('ix_pass_stamps_pass_when', 'pass_stamps', ['pass_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pass_stamps_qr_token_jti'), 'pass_stamps', ['qr_token_jti'], unique=False)
    op.create_index(op.f('ix_pass_stamps_tenant_id'), 'pass_stamps', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('method', sa.Enum('MERCADO_PAGO', 'TRANSFER', 'CASH', 'CARD_ON_DELIVERY', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED', 'CANCELED', name='payment_status'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('provider_preference_id', sa.String(length=120), nullable=True),
    sa.Column('provider_status_detail', sa.String(length=200), nullable=True),
    sa.Column('init_point', sa.String(length=500), nullable=True),
    sa.Column('sandbox_init_point', sa.String(length=500), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_preference_id'), 'payments', ['provider_preference_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_pass', app.models.base.GUID(), nullable=True),
    sa.Column('consumed_by_user', app.models.base.GUID(), nullable=True),
    sa.Column('device_fp', sa.String(length=64), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['loyalty_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consumed_by_pass'], ['customer_passes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consumed_by_user'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_campaign_id'), 'qr_tokens', ['campaign_id'], unique=False)
    op.create_index('ix_qr_tokens_expires', 'qr_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_qr_tokens_jti'), 'qr_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_qr_tokens_tenant_id'), 'qr_tokens', ['tenant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='quote_status'), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=True),
    sa.Column('branch_id', app.models.base.GUID(), nullable=True),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=40), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_token', sa.String(length=40), nullable=False),
    sa.Column('converted_order_id', app.models.base.GUID(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_branch_id'), 'quotes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_quotes_customer_id'), 'quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotes_number'), 'quotes', ['number'], unique=False)
    op.create_index(op.f('ix_quotes_public_token'), 'quotes', ['public_token'], unique=True)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    op.create_table('recetas',
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('insumo_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_insumo_id'), 'recetas', ['insumo_id'], unique=False)
    op.create_index(op.f('ix_recetas_product_id'), 'recetas', ['product_id'], unique=False)
    op.create_index(op.f('ix_recetas_tenant_id'), 'recetas', ['tenant_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('quote_id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_recetas_tenant_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_product_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_insumo_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_public_token'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_customer_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_branch_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_qr_tokens_tenant_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_jti'), table_name='qr_tokens')
    op.drop_index('ix_qr_tokens_expires', table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_campaign_id'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_preference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_pass_stamps_tenant_id'), table_name='pass_stamps')
    op.drop_index(op.f('ix_pass_stamps_qr_token_jti'), table_name='pass_stamps')
    op.drop_index('ix_pass_stamps_pass_when', table_name='pass_stamps')
    op.drop_index(op.f('ix_pass_stamps_pass_id'), table_name='pass_stamps')
    op.drop_table('pass_stamps')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_branch_products_tenant_id'), table_name='branch_products')
    op.drop_index(op.f('ix_branch_products_product_id'), table_name='branch_products')
    op.drop_index(op.f('ix_branch_products_branch_id'), table_name='branch_products')
    op.drop_table('branch_products')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_starts_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_branch_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_ai_traces_tenant_id'), table_name='ai_traces')
    op.drop_index(op.f('ix_ai_traces_step'), table_name='ai_traces')
    op.drop_index(op.f('ix_ai_traces_log_id'), table_name='ai_traces')
    op.drop_index(op.f('ix_ai_traces_conversation_id'), table_name='ai_traces')
    op.drop_table('ai_traces')
    op.drop_index(op.f('ix_qr_codes_tenant_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_target_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_short_code'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_branch_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_qr_code_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_passes_tenant_status', table_name='customer_passes')
    op.drop_index(op.f('ix_customer_passes_tenant_id'), table_name='customer_passes')
    op.drop_index(op.f('ix_customer_passes_customer_id'), table_name='customer_passes')
    op.drop_index(op.f('ix_customer_passes_campaign_id'), table_name='customer_passes')
    op.drop_table('customer_passes')
    op.drop_index(op.f('ix_carts_tenant_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_session_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_customer_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_tenant_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_logs_user_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_tenant_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_status'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_conversation_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_agent'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_uploads_tenant_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_entity_type'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_entity_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_promotions_tenant_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_onboarding_states_tenant_id'), table_name='onboarding_states')
    op.drop_table('onboarding_states')
    op.drop_index(op.f('ix_loyalty_campaigns_tenant_id'), table_name='loyalty_campaigns')
    op.drop_index('ix_loyalty_campaigns_tenant_active', table_name='loyalty_campaigns')
    op.drop_table('loyalty_campaigns')
    op.drop_index(op.f('ix_landing_configs_tenant_id'), table_name='landing_configs')
    op.drop_table('landing_configs')
    op.drop_index(op.f('ix_insumos_tenant_id'), table_name='insumos')
    op.drop_index(op.f('ix_insumos_sku'), table_name='insumos')
    op.drop_index(op.f('ix_insumos_name'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_business_costs_tenant_id'), table_name='business_costs')
    op.drop_table('business_costs')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_automation_executions_user_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_tenant_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_status'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_source_insight_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_action_type'), table_name='automation_executions')
    op.drop_index('ix_auto_exec_user_created', table_name='automation_executions')
    op.drop_index('ix_auto_exec_tenant_created', table_name='automation_executions')
    op.drop_index('ix_auto_exec_action', table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_type'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_actor', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_metrics_daily_tenant_id'), table_name='ai_metrics_daily')
    op.drop_index(op.f('ix_ai_metrics_daily_day'), table_name='ai_metrics_daily')
    op.drop_index(op.f('ix_ai_metrics_daily_agent'), table_name='ai_metrics_daily')
    op.drop_table('ai_metrics_daily')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_tenant_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_status'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_industry'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('site_config')
    op.drop_index(op.f('ix_legal_consents_user_id'), table_name='legal_consents')
    op.drop_index(op.f('ix_legal_consents_document_type'), table_name='legal_consents')
    op.drop_table('legal_consents')
    # ### end Alembic commands ###
